set_property SRC_FILE_INFO {cfile:{F:/Git Projects/EIT/P7---Bsc/Code/VHDL/ADCControlFinal/ADCControlFinal.srcs/constrs_1/imports/Transfer/Cmod-A7-Master.xdc} rfile:../../../ADCControlFinal.srcs/constrs_1/imports/Transfer/Cmod-A7-Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN K2 [get_ports EXT_EXT_CNV_ACQUIRE_EXT_ADC_CONTROL_TO_ADC_A_AND_B_OUT]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J3 [get_ports EXT_EXT_SCK_POS_ADC_CONTROL_TO_ADC_A_OUT]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T3 [get_ports EXT_EXT_SCK_POS_ADC_CONTROL_TO_ADC_B_OUT]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN B15 [get_ports EXT_EXT_SDA_POS_ADC_A_TO_ADC_CONTROL_IN]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN R3 [get_ports EXT_EXT_SDA_POS_ADC_B_TO_ADC_CONTROL_IN]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN C15 [get_ports EXT_TEST_ACQUIRE_START]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports EXT_TEST_ACQUIRE_START]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L17 [get_ports MASTER_CLK_IN]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[15]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[14]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[13]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[12]}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[11]}]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[10]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[9]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[8]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[7]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[6]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[5]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[4]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[3]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[2]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[1]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS25 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[0]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W4 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[7]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V5 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[6]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U4 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[5]}]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V4 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[4]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W5 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[3]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V3 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[2]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W3 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[1]}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V2 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[0]}]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U5 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[8]}]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U2 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[9]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W6 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[10]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U3 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[11]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U7 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[12]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN W7 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[13]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN U8 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[14]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN V8 [get_ports {EXT_LEDS_DATA_FROM_ADC_CONTROL[15]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[15]]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[14]]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[13]]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[12]]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[11]]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[10]]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[9]]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[8]]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[7]]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[6]]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[5]]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[4]]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[3]]
set_property src_info {type:XDC file:1 line:202 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[2]]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[1]]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property OFFCHIP_TERM NONE [get_ports EXT_LEDS_DATA_FROM_ADC_CONTROL[0]]
