set_property PACKAGE_PIN A18 [get_ports CLK]
set_property IOSTANDARD LVCMOS33 [get_ports CLK]
set_property PACKAGE_PIN A17 [get_ports LED1]
set_property PACKAGE_PIN C16 [get_ports LED2]
set_property IOSTANDARD LVCMOS33 [get_ports LED1]
set_property IOSTANDARD LVCMOS33 [get_ports LED2]

set_property PACKAGE_PIN L17 [get_ports CLK_CRYSTAL]
set_property PACKAGE_PIN R3 [get_ports CLK_OUT]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_CRYSTAL]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT]

set_property PACKAGE_PIN L17 [get_ports clk_in1_0]
set_property PACKAGE_PIN A18 [get_ports CLK_0]
set_property PACKAGE_PIN A17 [get_ports LED2_0]
set_property PACKAGE_PIN C16 [get_ports LED1_0]
set_property PACKAGE_PIN R3 [get_ports CLK_OUT_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_0]
set_property IOSTANDARD LVCMOS33 [get_ports LED1_0]
set_property IOSTANDARD LVCMOS33 [get_ports LED2_0]
