# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/CMOD A7 AT35 Constraint File/Cmod-A7-Master.xdc

# XDC: new/cmod_17_master_constraint_blinky.xdc

# Block Designs: bd/clk/clk.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk || ORIG_REF_NAME==clk} -quiet] -quiet

# IP: bd/clk/ip/clk_clk_wiz_0_0/clk_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_clk_wiz_0_0 || ORIG_REF_NAME==clk_clk_wiz_0_0} -quiet] -quiet

# IP: bd/clk/ip/clk_blinkymcblink_0_0/clk_blinkymcblink_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_blinkymcblink_0_0 || ORIG_REF_NAME==clk_blinkymcblink_0_0} -quiet] -quiet

# XDC: c:/EIT GIT/P7---Bsc/Code/VHDL/Test/Test.gen/sources_1/bd/clk/clk_ooc.xdc
